cheetos:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  front_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: LeftWheel
    pid: {p: 1.0, i: 0.01, d: 0.001}
    
  front_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: RightWheel
    pid: {p: 1.0, i: 0.01, d: 0.001}

  suspension_front_left:
    type: effort_controllers/JointPositionController
    joint: LeftSuspension
    #pid: {p: 100, i: 0.001, d: 30}
    pid: {p: 100, i: 0.00, d: 0}

  suspension_front_right:
    type: effort_controllers/JointPositionController
    joint: RightSuspension
    #pid: {p: 100, i: 0.001, d: 30}
    pid: {p: 100, i: 0.00, d: 0}

  suspension_rear:
    type: effort_controllers/JointPositionController
    joint: RearSuspension
    #pid: {p: 100, i: 0.001, d: 30}
    pid: {p: 100, i: 0.00, d: 0}